/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;


import javax.swing.JOptionPane;  

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ELouanes
 */
public class Serveur
    extends
    javax.swing.JFrame
{

    private int Port;
    ServeurImpl Impl;
    String SendMSG;

    public Serveur()
    {
        initComponents();
    }

    // ADD USER
    public void ADDUSER(String user)
    {
        jTextArea2.append(user + "\n");
        jTextArea1.append(">>" + user + " is login\n");
    }

    // logout USER
    public void DELUSER(String user)
    {

        jTextArea1.append(">>" + user + " is logOUT\n");
    }

    // ADD MSG
    public void ADDMSG(String user, String MSG)
    {
        jTextArea1.append(user + " >> " + MSG + "\n");
    }

    // Send MSG
    public String SENDMASG()
    {
        return SendMSG;
    }

    // Start Sarver
    private boolean startServer(int port)
    {
        try
        {
            // create on port 1099
            Registry registry = LocateRegistry.createRegistry(port);
            // create a new service named myMessage
            registry.rebind("myMessage", Impl);
            return true;
        }
        catch (Exception e)
        {
            e.printStackTrace();
            return false;
        }
    }

    private boolean StopServer()
    {
        try
        {
            Registry reg = LocateRegistry.getRegistry(Port);
            reg.unbind("myMessage");
            return true;
        }
        catch (Exception e)
        {
            e.printStackTrace();
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextFieldSend = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EpAAA Serveur");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter()
            {
                public void windowOpened(java.awt.event.WindowEvent evt)
                {
                    formWindowOpened(evt);
                }
            });

        jLabel1.setText("Port");

        jTextFieldPort.setText("1099");

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/network_16x16.png"))); // NOI18N
        jButtonStart.setText("Start Server");
        jButtonStart.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButtonStartActionPerformed(evt);
                }
            });

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eject_16x16.png"))); // NOI18N
        jButtonStop.setText("Stop Server");
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButtonStopActionPerformed(evt);
                }
            });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButtonSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/letter-opened_16x16.png"))); // NOI18N
        jButtonSend.setText("Send");
        jButtonSend.setEnabled(false);
        jButtonSend.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButtonSendActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                                             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                         false)
                                                                                                    .addComponent(jTextFieldSend)
                                                                                                    .addComponent(jScrollPane1,
                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                  358,
                                                                                                                  Short.MAX_VALUE))
                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jScrollPane2)
                                                                                                    .addComponent(jButtonSend,
                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                  Short.MAX_VALUE))
                                                                             .addContainerGap()));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                       false)
                                                                                                  .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                181,
                                                                                                                Short.MAX_VALUE)
                                                                                                  .addComponent(jScrollPane2))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                  .addComponent(jTextFieldSend,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                  .addComponent(jButtonSend))
                                                                           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                            Short.MAX_VALUE)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder_16x16.png"))); // NOI18N
        jButton1.setText("Open Files Folder");
        jButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton1ActionPerformed(evt);
                }
            });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/round-question_16x16.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter()
            {
                public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    jLabel2MouseClicked(evt);
                }
            });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jPanel2,
                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                  Short.MAX_VALUE)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                           .addComponent(jLabel2)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                           .addComponent(jLabel1)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                           .addComponent(jTextFieldPort,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                         59,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                           .addComponent(jButtonStart)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                           .addComponent(jButtonStop)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                            82,
                                                                                                                                            Short.MAX_VALUE)
                                                                                                                           .addComponent(jButton1)))
                                                                             .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                  .addComponent(jLabel2)
                                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                         .addComponent(jLabel1)
                                                                                                                         .addComponent(jTextFieldPort,
                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                       javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                         .addComponent(jButtonStart)
                                                                                                                         .addComponent(jButtonStop)
                                                                                                                         .addComponent(jButton1)))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                           .addComponent(jPanel2,
                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                            Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)
    {// GEN-FIRST:event_formWindowOpened

        try
        {
            Impl = new ServeurImpl(this);
        }
        catch (RemoteException ex)
        {
            Logger.getLogger(Serveur.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/c",
                                                        "mkdir \"C:\\Users\\htira\\eclipse-workspace\\WebSocket project\\ServerRMI");
            builder.redirectErrorStream(true);
            builder.start();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }// GEN-LAST:event_formWindowOpened

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButtonStartActionPerformed
        Port = Integer.valueOf(jTextFieldPort.getText());
        if (startServer(Port))
        {
            jTextArea1.append(">>Serveur Start\n");
            jButtonStart.setEnabled(false);
            jButtonStop.setEnabled(true);
            jButtonSend.setEnabled(true);
        }
        else
        {
            jTextArea1.append(">>Serveyr Fail Try change port\n");
        }

    }// GEN-LAST:event_jButtonStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton1ActionPerformed

        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "
                                      + "C:\\Users\\htira\\eclipse-workspace\\WebSocket project\\ServerRMI");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButtonStopActionPerformed

        if (StopServer())
        {
            jTextArea1.append(">>Serveur Stop\n");
            jTextArea2.setText("");
            jButtonStart.setEnabled(true);
            jButtonStop.setEnabled(false);
            jButtonSend.setEnabled(false);
        }
    }// GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButtonSendActionPerformed
        SendMSG = jTextFieldSend.getText();

    }// GEN-LAST:event_jButtonSendActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt)
    {// GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(rootPane, "Bouguerra Elouanes \nMenacer Abderaouf \nBenrekia Mamoune"
                                                + "\nAbdellah Khater Esam \nBourabia Ahmed \nEncadré par :  Mr.Rahim  \nUniv Medea");
    }// GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new Serveur().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldSend;
    // End of variables declaration//GEN-END:variables
}
